volunteerlogging/config/routes.rb
Rails.application.routes.draw do
  resources :sections

  resources :events
  mount RailsAdmin::Engine => '/super_admin', as: 'rails_admin'
  devise_for :admins, path: 'admin', controllers: { sessions: "admins/sessions" , registrations: "admins/registrations"}
  devise_for :volunteers, path: 'volunteer', controllers: { sessions: "volunteers/sessions" , registrations: "volunteers/registrations"}
  
  

  root 'pages#home'  
  get 'pages/home'

  get 'event/showEvent', to: 'events#showEvent', as: "eshow"  
  get 'event/sections', to: 'events#sections'
  get 'create_event', to: 'events#create_event'
  post 'sign_up', to: 'events#sign_up'
  get 'signed_in', to: 'application#current_user'
  post 'leave', to: 'events#leave'
  post 'event/create_sections', to: 'events#createSections'
  get  'event/create_sections', to: 'events#new'
  get 'section', to: "events#eventSections"
  get 'admin_cal', to: "events#admin_cal"
  get 'updateCal', to: "events#updateCal"

  get 'pages/about'
  get 'volunteers/home', to: 'volunteers#home'
  get 'volunteers/descriptions', to:'volunteers#descriptions'
  get 'volunteers/hoursworked', to: "volunteers#hoursworked"

  get 'admins/dashboard', to: 'admins#dashboard'
  get 'admins/volunteers', to: 'admins#volunteers'
   get 'admins/volunteers/:id', to: 'volunteers#show'
  get 'admins/volunteers/:id/edit', to: 'volunteers#edit'
  delete 'admins/volunteers/:id', to: 'volunteers#destroy'
  get 'admins/log_hours', to: 'hours#new'
  post 'admins/log_hours', to: 'hours#create'
  get 'admins/register', to: 'volunteers#new'
  get 'admins/reports', to: 'reports#reports'
  get 'admins/email', to: 'admins#email_users'
  post 'admins/email', to: 'admins#send_emails'

  get 'calendar', to: 'calendar#calendar'

  resources :admins, :controller => 'admins'
  resources :volunteer_descriptions
  resources :volunteers
  resources :hours
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

volunteerlogging/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

volunteerlogging/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

volunteerlogging/app/models/event.rb
class Event < ApplicationRecord
    has_many :sections
end

volunteerlogging/app/models/event_repeated.rb
class EventRepeated < ApplicationRecord
end

volunteerlogging/app/models/hour.rb
class Hour < ApplicationRecord
	belongs_to :volunteer
	belongs_to :section
end

volunteerlogging/app/models/section.rb
class Section < ApplicationRecord
    belongs_to :event
    has_many :hours
end

volunteerlogging/app/models/user.rb
class User < ApplicationRecord
 
end

volunteerlogging/app/models/volunteer.rb
class Volunteer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_one :volunteer_description
	has_many :hours
end

volunteerlogging/app/models/volunteer_description.rb
class VolunteerDescription < ApplicationRecord
	belongs_to :volunteers
end

volunteerlogging/app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_hour, only: [:show, :edit, :update, :destroy]

  # GET /hours
  # GET /hours.json
  def index
    @hours = Hour.all
  end

  # GET /hours/1
  # GET /hours/1.json
  def show
  end

  # GET /hours/new
  def new
    @hour = Hour.new
    @volunteers = Volunteer.all
  end

  # GET /hours/1/edit
  def edit
  end

  # POST /hours
  # POST /hours.json
  def create
    @hour = Hour.new(hour_params)

    respond_to do |format|
      if @hour.save
        format.html { redirect_to '/admins/log_hours', notice: 'Hour was successfully created.' }
        format.json { render :show, status: :created, location: @hour }
      else
        format.html { render :new }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hours/1
  # PATCH/PUT /hours/1.json
  def update
    respond_to do |format|
      if @hour.update(hour_params)
        format.html { redirect_to '/admins/log_hours', notice: 'Hour was successfully updated.' }
        format.json { render :show, status: :ok, location: @hour }
      else
        format.html { render :edit }
        format.json { render json: @hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hours/1
  # DELETE /hours/1.json
  def destroy
    @hour.destroy
    respond_to do |format|
      format.html { redirect_to hours_url, notice: 'Hour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hour
      @hour = Hour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hour_params
      params.require(:hour).permit(:hour_id, :hoursWorked, :weekWorked, :volunteer_id, :section_id)
    end
end

volunteerlogging/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end


end

volunteerlogging/app/helpers/admins_helper.rb
module AdminsHelper
end

volunteerlogging/app/helpers/application_helper.rb
module ApplicationHelper
end

volunteerlogging/app/helpers/calendar_helper.rb
module CalendarHelper
end

volunteerlogging/app/helpers/events_helper.rb
module EventsHelper
end

volunteerlogging/app/helpers/hours_helper.rb
module HoursHelper
end

volunteerlogging/app/helpers/pages_helper.rb
module PagesHelper
end

volunteerlogging/app/helpers/reports_helper.rb
module ReportsHelper
end

volunteerlogging/app/helpers/sections_helper.rb
module SectionsHelper
end

volunteerlogging/app/helpers/volunteers_helper.rb
module VolunteersHelper
end

volunteerlogging/app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  

  <div class="field">
    <%= form.label :adminId %>
    <%= form.number_field :adminId, id: :admin_adminId %>
  </div>

  <div class="field">
    <%= form.label :firstName %>
    <%= form.text_field :firstName, id: :admin_firstName %>
  </div>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName, id: :admin_lastName %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :admin_email %>
  </div>

  <div class="field">
    <%= form.label :encrypted_password %>
    <%= form.text_field :encrypted_password, id: :admin_encrypted_password %>
  </div>

  <div class="field">
    <%= form.label :dateJoined %>
    <%= form.date_select :dateJoined, id: :admin_dateJoined %>
  </div>

  <div class="field">
    <%= form.label :phoneNum %>
    <%= form.text_field :phoneNum, id: :admin_phoneNum %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

volunteerlogging/app/views/admins/dashboard.html.erb
<style>
background {
    width: 100%;
}
.welcome {
  padding: 10px;
  border-radius: 15px;
  margin-left: 20%;
  text-align: center;
  color: white;
  background-color: #00467f;
  height: 80px;
  width: 400px;

}
button {
    height: 200px;
    width: 300px;
    margin-top: 20px;
    background-color: white;

} h1 {
    font-size: 25px;
}
button[name="email"], button[name="report"] {
    margin-top: 8%;
}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<div id="container" style= "margin-top: -3%; " id="Ndiv" class="col-10 offset-1 offset-lg-2">
  <h2 class="welcome">Welcome, Admin</h2>


            <button id="volunteer" class = "btn  col-5 col-lg-4">
               <h1 id="volunteer" >Volunteers</h1>
            </button>


            <button id="loghours" class = "btn col-5  col-lg-4 offset-1 ">
               <h1 id="loghours">Log Hours</h1>
            </button>


            <button id="emails" name="email" class = "btn col-5 col-lg-4">
                <h1 id="emails">Send Emails</h1>
            </button>


            <button id="reports" name="report" class = "btn btn-lrg col-5 col-lg-4 offset-1">
                <h1 id="reports" >Reports</h1>
            </button>

</div>

<script>

$("button").click(function(e){
    $("#container").hide();
   switch(e.target.id){
       case "volunteer":
           window.location = "volunteers";
           break;
        case "loghours":
           window.location = "/admin_cal";
           break;
        case "emails":
           window.location = "email";
           break;
        case "reports":
            window.location = "reports";
            break;
        case "empty":
            $("#results").html(" ");
            $("#container").show();
            break;

   }
});
</script>

volunteerlogging/app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

volunteerlogging/app/views/admins/email_users.html.erb
<style>
.jumbotron {
    
    background-color: white;
    margin-top: 5%;
    
    max-height: 600px;
}


#groups, #volunteers {
    max-height: 450px;
    overflow: auto;
}

ul {
    list-style-type: none;
}
</style>

<div class="jumbotron col-10 offset-1">
    
    <%= form_tag do %>
    <div id="holder" class="row col-12">
    <div id = "email" class="col-6 ">
        <div class="row col-12">
        <%= label_tag( :subjectL, "Subject:" , :class=>" col-2   ") %>
        <%= text_field_tag(:subject , "Subject", :class=>"form-control col-8") %>
        </div>
        <br>
        <div class"row col-12">
       <textarea id="eBody" class='wysihtml5 form-control col-3 offset-1' placeholder="Enter text ..."></textarea>
        </div>
        <br>
        <button id="sendEmail" type="button" class="btn btn-primary col-3 offset-1 ">Send Email</button>
    </div>
    <div id="select" class="col-6">
        <div class="row col-12">
        <div class="row col-12 ">
            <h4 class=" offset-3"> Select People/Group </h4>
        </div>
        <div class="col-5">
            <div class="row col-12">
                <label class="col-12 text-center">Groups</label>
            
            <div id="groups">
            </div>
            </div>
        </div>
        <div class="col-5 offset-1">
            <div class="row col-12">
                <label class="col-5">Volunteers:</label><input id="name" class="form-control col-6 offset-1">
            
            <br>
            <div id="volunteers">
                
            </div></div>
        </div>
        </div>
    </div>
    </div>
    <% end %>
    <br><br>
    <div class="row col-12">
        <%= link_to "back", "/admins/dashboard", :class=>" btn col-1 offset-10"%>
        
    </div>
    <br>
</div>

<script>




$(document).on('page:load', function(){
  window['rangy'].initialized = false
});


var allVols = <%= @volunteers.to_json.html_safe %>
var groups = <%= @groups.to_json.html_safe %>
var send = {};
  $(document).ready(function(){
  
  $('.wysihtml5').each(function(i, elem) {
      $(elem).wysihtml5({
          'toolbox':{
              'color': true,
              'lists': true,
      'html': true,
      'link': true,
      'image': true,
          }
      });
    });

  var vlist = "<ul id='volunteersList' class='list-unstyled'>";
  $.each(allVols, function(key, obj){
    vlist += "<li class='col-10' name ='vol' id='"+ obj.firstName + " " + obj.lastName+ "' ><input type='checkbox' class='checkbox col-2' name='volunteers' value='" + obj.email +"'><label class='col-8'>  " + obj.firstName + " " + obj.lastName+ "</label></li>";
  });
  vlist +="</ul>";
  
  $("#volunteers").html(vlist);

  $("li[name='vol']").each(function(){
    $(this).hide();
  });

    
    var gmap = {};
    $.each(groups, function(key, group){
        gmap[group.Voltype] = group.Voltype;

    });
     var glist =  "<ul id='groupList' class='col-12'>";
    $.each(gmap, function(key, value){
       glist += "<li style=' ' class='col-12' id='"+ key +  "' ><input type='checkbox' class='checkbox col-2' name='groups' value='" + key+ "'><label>"+key +"</label></li>";

    });
    glist += "</ul>";

    $("#groups").html(glist);
});

$("#name ").keyup(function(e){
    $(" li[name='vol']").each(function(){
      var str = this.id.toLowerCase();
   
      var filter = e.target.value.toLowerCase();
      var res = str.match("(.*|\s?)"+filter+".*");
      if(e.target.value == "")
        $("#volunteers").hide();
      else
        $("#volunteers").show();
      
      if(res != null)
        $(this).show();
      else
        $(this).hide();
    });
  });


    $("button").click(function(){
        var userlist = {};
        var emailUsers = $("input[name='volunteers']:checked");
            emailUsers.each(function(){
                userlist[this.value] = this.value
            });
    var emailGroups = $("input[name='groups']:checked");
            var grouplist = {};
            emailGroups.each(function(){
                grouplist[this.value] = this.value
            });
        var body = $("#eBody").val();
        var subject = $("#subject").val();

        $.ajax({
            url: "/admins/email",
            type: "post",
            dataType: "json",
            data: {"emailUsers": userlist,"emailGroups":grouplist, "ebody": body, "subject": subject },
            success: function(){
                alert("email sent");
            },
        });
    });
    
</script>

volunteerlogging/app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Adminid</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Datejoined</th>
      <th>Phonenum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.adminId %></td>
        <td><%= admin.firstName %></td>
        <td><%= admin.lastName %></td>
        <td><%= admin.email %></td>
        <td><%= admin.encrypted_password %></td>
        <td><%= admin.dateJoined %></td>
        <td><%= admin.phoneNum %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

volunteerlogging/app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

volunteerlogging/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

volunteerlogging/app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Adminid:</strong>
  <%= @admin.adminId %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @admin.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @admin.lastName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @admin.encrypted_password %>
</p>

<p>
  <strong>Datejoined:</strong>
  <%= @admin.dateJoined %>
</p>

<p>
  <strong>Phonenum:</strong>
  <%= @admin.phoneNum %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

volunteerlogging/app/views/admins/volunteers.html.erb
<style>
.jumbotron {
  margin-top: 10%;
  background-color:white;
}

table{
  margin-top: 5%;
  height: 450px;
}
</style>
<p id="notice"><%= notice %></p>


<div id ="" class="jumbotron col-10 offset-1 ">
<div class="row">
<h1 class="col-4 offset-4">Volunteers</h1>
<input  id="search" class="form-control col-3 offset-1" type="search" placeholder="Search">
</div>
<table class="table table-sm table-hover table-responsive">
  <thead>
    <tr>
      <th id="volunteer_id"  > Volunteer ID</th>
      <th id="firstName" >Firstname</th>
      <th id="lastName">Lastname</th>
      <th id="email">Email</th>
      <th id="created_at">Datejoined</th>
      <th id="phoneNum">Phonenum</th>
      <th id="volType">Voltype</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
<div class="row"> 
<%= link_to 'New Volunteer', '/volunteers/new' , :class=>"btn col-3"  %>
<%= link_to 'Back', '/admins/dashboard', :class=>"btn col-2 offset-7"%>
</div>
</div>

<br>


<script>

  var data = <%= @volunteers.to_json.html_safe %>

  function sortrows(cat, e ){

  data.sort(function(a,b){
    var a1 = a[cat], b1 = b[cat];
    if((typeof a1) == 'string'){
      return a1.localeCompare(b1);
    }else{
      if(a1 == b1 ) return 0;
      return a1 > b1? 1: -1;
    }
  });

  var tbody = "";
  $.each(data, function(key, obj){
    
    tbody +="<tr class='trs'  id='"+ obj.volunteer_id + "'>";
    tbody += "<td>"+ obj.volunteer_id + "</td>";
    tbody += "<td id='firstName' value='"+ obj.firstName + "' >"+ obj.firstName + "</td>";
    tbody += "<td id='lastName'>"+ obj.lastName + "</td>";
    tbody += "<td>"+ obj.email + "</td>";
    tbody += "<td>"+ obj.created_at + "</td>";
    tbody += "<td>"+ obj.phoneNum + "</td>";
    tbody += "<td>"+ obj.volType + "</td>";
    tbody += "<td><a href='volunteers/"+ obj.id +"'>Show</a></td>";
    tbody += "<td><a href='volunteers/"+ obj.id +"/edit'>Edit</a></td>";
    tbody += "<td><a data-method='delete' href='volunteers/"+ obj.id +"'>Delete</a></td>";
    tbody += "</tr>";
  });
  
  $("tbody").html(tbody);

  }

$("#search").keyup(function(e){
    $("table .trs").each(function(){
      var str = $(this).children("#firstName").text().toLowerCase() + " " + $(this).children("#lastName").text().toLowerCase();
   
      var filter = e.target.value.toLowerCase();
      
      var res = str.match("(.*|\s?)"+filter+".*");
      
      if(res == null)
        $(this).hide();
      else
        $(this).show();
    });
  });  

  $("th").click(function(e){
    sortrows(e.target.id);
  });

  
  sortrows("id");
</script>

volunteerlogging/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

volunteerlogging/app/views/pages/home.html.erb
    <style>
        button {
            width: 100%;
            height: 200px;
            background-color: white;
        }
        .welcome {
        	padding: 10px;
        	border-radius: 15px;
        	margin-left: 24%;
        	text-align: center;
        	color: white;
        	background-color: #00467f;
        	height: 100px;
        	width: 700px;

        }
    </style>
    <h1 class = "welcome"; align = "center"; style = "font-size:50px; color:white; margin-top: 10%; text-shadow: 2px 2px black;">Welcome to Libby's Place</h1>
   <div id="Ndiv"  style="margin-top:3%; height:75%;" class="row col-10 offset-1">
    <div id="Ndiv" class="col-6">
        <button id="volun"  class="btn">
            <h3 class="display-8">I am a Volunteer</h3>
        </button>
    </div>
    <div id="Ndiv" class="col-6 ">
        <button id="admin"   class="btn">
            <h3 id="admin" class="display-8">I am an Admin</h3>
        </button>
    </div>
    </div>

    <div id="adminLogin">
    </div>


<img  id="cat" alt="transparent black cat gif" class="main" data-link="/gifs/43971-transparent-black-cat-gif" oncontextmenu="_gaq.push(['_trackEvent', 'gif', 'copy', $(this).data('link')], ['_trackEvent', 'gif', 'copy-from', 'detail']); " style="height:200px; width: 200px;" src="http://25.media.tumblr.com/9f0a84c8bd80809383fcbc84f7cef424/tumblr_mg6gnlOORA1r933q9o1_500.gif" title="transparent black cat gif">


     <script>

    $(document).on("mousemove", function(event){
        
        $("#cat").css({top: event.pageY - 100  , left: event.pageX - 200, position: 'absolute'});
       
    });


        $("button").click(function(e){
            $("button").hide();
            if(e.target.id == "admin"){
                if (<%=admin_signed_in?=%>) {
                    window.location = "/admins/dashboard";
                 }else
                window.location = "/admin/sign_in";
            }else{
                if (<%=volunteer_signed_in?=%>) {
                    window.location = "/volunteers/home"
                }
                else
                window.location = "/volunteer/sign_in";
            }

        });

    </script>