volunteerlogging/config/routes.rb
Rails.application.routes.draw do
  resources :sections

  resources :events
  mount RailsAdmin::Engine => '/super_admin', as: 'rails_admin'
  devise_for :admins, path: 'admin', controllers: { sessions: "admins/sessions" , registrations: "admins/registrations"}
  devise_for :volunteers, path: 'volunteer', controllers: { sessions: "volunteers/sessions" , registrations: "volunteers/registrations"}
  
  

  root 'pages#home'  
  get 'pages/home'

  get 'event/showEvent', to: 'events#showEvent', as: "eshow"  
  get 'event/sections', to: 'events#sections'
  get 'create_event', to: 'events#create_event'
  post 'sign_up', to: 'events#sign_up'
  get 'signed_in', to: 'application#current_user'
  post 'leave', to: 'events#leave'
  post 'event/create_sections', to: 'events#createSections'
  get  'event/create_sections', to: 'events#new'
  get 'section', to: "events#eventSections"
  get 'admin_cal', to: "events#admin_cal"
  get 'updateCal', to: "events#updateCal"

  get 'pages/about'
  get 'volunteers/home', to: 'volunteers#home'
  get 'volunteers/descriptions', to:'volunteers#descriptions'
  get 'volunteers/hoursworked', to: "volunteers#hoursworked"

  get 'admins/dashboard', to: 'admins#dashboard'
  get 'admins/volunteers', to: 'admins#volunteers'
   get 'admins/volunteers/:id', to: 'volunteers#show'
  get 'admins/volunteers/:id/edit', to: 'volunteers#edit'
  delete 'admins/volunteers/:id', to: 'volunteers#destroy'
  get 'admins/log_hours', to: 'hours#new'
  post 'admins/log_hours', to: 'hours#create'
  get 'admins/register', to: 'volunteers#new'
  get 'admins/reports', to: 'reports#reports'
  get 'admins/email', to: 'admins#email_users'
  post 'admins/email', to: 'admins#send_emails'

  get 'calendar', to: 'calendar#calendar'

  resources :admins, :controller => 'admins'
  resources :volunteer_descriptions
  resources :volunteers
  resources :hours
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

volunteerlogging/app/models/event.rb
class Event < ApplicationRecord
    has_many :sections
end

volunteerlogging/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy            ]
  before_action :authenticate_admin!, only: [:admin_cal, :createSections]
  respond_to :html, :js
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end


  def create_event
  end

  def admin_cal
    @volunteers = Volunteer.all
  end
  
  def sign_up    

    hr = params['hour']
   
    params['hour']['approved'] = "false"
   
    
    month = Event.find_by_sql("select start_time from events where id = (select event_id from sections where id = #{params["hour"]["section_id"]})")
    mon= "#{month[0]["start_time"]}"
    
    params["hour"]["weekWorked"] = mon
    params["hour"]["approved"] = false
    @hour = Hour.new(hour_params)
    
      
    respond_to do |format|
      if @hour.save
        format.json { render '/events/index' }
      else
        format.json { render '/events/index'}
      end
    end
  end

  def leave
    v_id =params["hour"]["volunteer_id"]
    section= params["hour"]["section_id"]
    hr_id = Hour.find_by_sql("select id from hours where section_id = #{section} and volunteer_id = #{v_id}")
              
    hour = Hour.find(hr_id[0].id)
    hour.destroy
    respond_to do |format|
      format.json { render '/events/index' }
    end
  end

  def createSections
    
    @event = params["event"]
    repeated = params["event_repeated"]
    @newevent = Event.new(event_params)
    @newevent.save
  
    startTime = event["start_time(4i)"].to_i
    endTime = event["end_time(4i)"].to_i
    
    num =  startTime + (endTime - startTime)
   
    eid = Event.find_by_sql("select id, repeated_id from events order by id desc limit 1")
    
     for i in startTime..num 
    
      params['section'] = {"start(1i)"=> event["start_time(1i)"],
                      "start(2i)" => event["start_time(2i)"],
                      "start(3i)" => event["start_time(3i)"],
                      "start(4i)" => "#{i}",
                      "start(5i)" => event["start_time(5i)"],
                      "end(1i)"=> event["end_time(1i)"],
                      "end(2i)" => event["end_time(2i)"],
                      "end(3i)" => event["end_time(3i)"],
                      "end(4i)" => "#{i + 1}",
                      "end(5i)" => event["end_time(5i)"],
                      "event_id" => eid[0].id,
                      "event_section" => "#{i + 1 - startTime}"
                      
                     }
                     puts params['section']
      section = Section.new(section_params)
      section.save
    end
    
    respond_to do |format|
      format.html {redirect_to "/admin_cal"}
      
    end
    
  end

  def showEvent
    @hour = Hour.new
    eid = params["id"]
    secs = Volunteer.find_by_sql("select id,start,end from sections where event_id = #{eid}")
    @descrition = Event.find_by_sql("select description from events where id = #{eid}")
    count = 0
    @dataHash = Hash.new
    @dataHash["desc"] = @descrition 
    @dataHash[0] = secs
    secs.each do |sec|
      @dataHash[sec.id] = Volunteer.find_by_sql("select firstName, lastName, id from
     volunteers where id in (select volunteer_id from hours where
     section_id in (select id from sections where id = #{sec.id}))")
     count = 1 + count
    end
    
    respond_to do |format|
      format.json {render json: @dataHash }

    end
  end

  def eventSections
    respond_to do |format|
      format.html {render "/event/"}
      format.json {render "/event/sections"}
    end
  end


  # GET /events/1
  # GET /events/1.json
  def show
  end


  
  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def updateCal
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_time, :end_time, :numOfSections)
    end

    def hour_params
      params.require(:hour).permit(:hour_id, :approved, :hoursWorked, :weekWorked, :volunteer_id, :section_id)
    end

    def section_params
      
      params.require(:section).permit(:event_id, :start, :end, :event_section)
    end
end

volunteerlogging/app/helpers/events_helper.rb
module EventsHelper
end

volunteerlogging/app/views/events/_eventSec.html.erb
<div class="row col-10 offset-2">
<div class="col-4">
    <h2>Slot 1</h2>
    <div id = "name1">
    names go here
    </div>
</div>
<div class="col-4">
    <h2>Slot 2</h2>
    <div id = "name2">
    and here
    </div>
</div>
</div>

volunteerlogging/app/views/events/_form.html.erb
<style>
li{
  display:inline;
}
</style>
<div class="col-10 offset-1">
<%= form_for :event , url: "/event/create_sections", remote: true do |form| %>
 

  <div id="titleid" class="row col-12">
    <%= form.label :title, :class=>"col-2 text-right" %>
    <%= form.text_field :title, id: :event_title, :class=>"form-control col-8"%>
  </div>
  <br>

  <div class="row col-12">
    <%= form.label :description, :class=>"col-2 text-right"%>
    <%= form.text_area :description, id: :event_description, :class=>"form-control col-8" %>
  </div>
  <br>

  <div class="row col-12">
    <%= form.label :start_time, :class=>"col-2 text-right" %>
    <%= form.date_field :start_date, id: :event_start_date, :class=>"datepicker form-control col-4 "%>  <h2>-</h2>
    <%= form.time_field :start_times, id: :event_start_time, :class=>"timepicker form-control col-3" , :data_format=>"hh:mm"%>
    </div>
<br>
  <div class="row col-12">
    <%= form.label :end_time, :class=>"col-2 text-right" %>
    <%= form.date_field :end_date, id: :event_end_date, :class=>"datepicker form-control col-4", :data_format=>"hh:mm" %><h2>-</h2>
    <%= form.time_field :end_times, id: :event_end_time, :class=>"timepicker form-control col-3" , :data_format=>"hh:mm"%>
  </div>
  <br>

<% end %>
  <div >
  <button id="submitCreateForm" class="form-control col-3">Submit</button>
  </div>
<script>

$(".datepicker").change(function(){
  if($('#event_start_date').val() >= $('#event_end_date').val() ){
    $('#event_end_date').val($('#event_start_date').val()  );
  }
  
});

$("#event_start_time").change(function(){
  if($('#event_start_time').val() >= $('#event_end_time').val() ){
    $('#event_end_time').val($('#event_start_time').val() );
  }
});

$("#event_end_time").change(function(){
  if($('#event_start_time').val() >= $('#event_end_time').val() ){
    $('#event_end_time').val($('#event_start_time').val() );
  }
});


$("#submitCreateForm").click(function(){
var title = $("#event_title").val();
var desc = $("#event_description").val();
var start = $("#event_start_time_1i").val() + "-"+$("#event_start_time_2i").val() +"-"+$("#event_start_time_3i").val() +" "+$("#event_start_time_4i").val() +":" + $("#event_start_time_5i").val();
var endtime = $("#event_end_time_1i").val() + "-"+$("#event_end_time_2i").val() +"-"+$("#event_end_time_3i").val() +" "+$("#event_end_time_4i").val() +":" + $("#event_end_time_5i").val();


var start1 = $("#event_start_date").val().substr(0,4);
var start2 = $("#event_start_date").val().substr(5,2) ;
var start3= $("#event_start_date").val().substr(8,2);
var start4 = +$("#event_start_time").val().substr(0,2) ;
var start5= $("#event_start_time").val().substr(3,2);
var endtime1 = $("#event_end_date").val().substr(0,4);
var endtime2 = $("#event_end_date").val().substr(5,2);
var endtime3 = $("#event_end_date").val().substr(8,2);
var endtime4 = $("#event_end_time").val().substr(0,2);
var endtime5 = $("#event_end_time").val().substr(3,2);





var start =  $("#event_start_date").val() + " " +  $("#event_start_time").val();
var endtime =  $("#event_end_date").val()+ " "+$("#event_end_time").val();

  
  var event = {"title" :title ,
       "description" : desc,
       "start_time(1i)" : start1,
       "start_time(2i)" : start2,
       "start_time(3i)" : start3,
       "start_time(4i)" : start4,
       "start_time(5i)" : start5,
       "end_time(1i)" :  endtime1,
       "end_time(2i)" :  endtime2,
       "end_time(3i)" :  endtime3,
       "end_time(4i)" :  endtime4,
       "end_time(5i)" :  endtime5};

  
  
  $.ajax({
    url: "/event/create_sections",
    data: {"event" : event},
    type: "POST",
    success: function(result){
        

    },error: function(){}
  
  });
});

</script>

volunteerlogging/app/views/events/admin_cal.html.erb
<p id="notice"><%= notice %></p>


<style>


#cal-back {
    background-color: white;
    margin-top: 20px;
}

#search {
    max-height: 500px;
}

</style>
<div id="cal-back" class="jumbotron col-10 offset-1">
    <div class="row">
  <div id="calendar" class="col-8">
  </div>
    <div id="search"  class="col-4">
    <input id="name" type="search" class="form-control   col-6 offset-1" placeholder="Enter Name">
    <br>
    <br>
         <div id="results" class="col-12">
        </div>
        <br>
        
        <div id="signing_in" >
        

        
        </div>
    </div>

    <%= link_to :Dashboard, '/admins/dashboard', :class=>"btn col-2 offset-9"%>
    </div>
</div>


<script>
var initialize_calendar;
var vol;
var signing_in ={};
var allVols = <%= @volunteers.to_json.html_safe %>
  
  $(document).ready(function(){
  

  var list = "<ul id='mylist' class='list-unstyled'>";
  $.each(allVols, function(key, obj){
    list += "<li class='col-10' id='"+ obj.firstName + " " + obj.lastName+ "' ><input type='checkbox' class='checkbox col-2' name='" + obj.firstName + " " + obj.lastName+ "' value='"+ obj.id + "'><label class='col-8'>  " + obj.firstName + " " + obj.lastName+ "</label></li>";
  });
  list +="</ul>";
  
  $("#results").html(list);

  $("#mylist li").each(function(){
    $(this).hide();
  });
});


$("#modal").slideUp(0);

$.ajax({
    url: "/signed_in",
    type: "get",
    dataType: "json",
    success: function(data) {
         vol = data;
    }
});

initialize_calendar = function() {
    $('#calendar').fullCalendar({
        height: 500,
        width: 400,
        events: '/events.json',


        eventClick: function(event, jsEvent, view) {
            


            $.ajax({
                url: 'event/showEvent',
                dataType: "json",
                type: "GET",
                data: { id: event.id },
                success: function(data) {
                    $("#content").html("");
                    var desc = data["desc"]

                    $("#description").html("<h5>Description:</h5> " + desc[0]["description"]);
                    var a = "";
                    var count = 1;
                    var signup = true;

                    data[0].forEach(function(num) {
                        a = "<div id='slots" + count + "' class='col-4'>  <h3>Slot " + count + "</h3>";

                        var start = (num.start.substr(11, 2) % 12 == 0 ? 12 : num.start.substr(11, 2) % 12) + ":" + num.start.substr(14, 2) + (num.start.substr(11, 2) < 12 ? 'am' : 'pm');

                        var end = (num.end.substr(11, 2) % 12 == 0 ? 12 : num.end.substr(11, 2) % 12) + ":" + num.end.substr(14, 2) + (num.end.substr(11, 2) < 12 ? 'am' : 'pm');

                        a += "<p>" + start + " - " + end + "</p>";
                        a += "<ul id='slot"+ num.id +"' class='list-unstyled'>";
                        data[num.id].forEach(function(person) {
                           
                            
                                a += " <li> <small><button id='leave' name='"+ person.id +"' value='" + num.id + "' class='btn col-10 btn-sm btn-danger'>"+person.firstName + " " + person.lastName + "</button></small> </li><br>";

                           
                        });
                        a += "</ul><button  id='signup'  value='" + num.id + "' class='btn btn-md btn-primary'>Sign Up</button><br>";

                        a += "</div>";
                        $("#content").append(a);
                        count++;
                    });


                    $('#modal').slideDown("slow");

                },
                error: function() {
                    alert("didnt work");
                }
            });
            return false;
        },
        dayClick: function(date, jsEvent, view) {

           
          if(<%= current_admin.to_json.html_safe %>){
            $.getScript('/create_event', function(data) {
                $("#event_start_date").val(date.format());
                $("#event_end_date").val(date.format());
                 $("#event_start_time").val("08:00");
                 $("#event_end_time").val("09:00");
            
            });
          }
        }
    });


}
$(document).on('turbolinks:load', initialize_calendar);

$(document).on('click', 'button', function(event) {
    

    if (event.target.id == 'signup') {

        var notsigned = true;
        $("input[type='checkbox']:checked").each(function(){
           
            notsigned = false;
            var hour = { section_id: event.target.value, volunteer_id: this.value, hoursWorked: 1};
                var id= this.value;
                var name= this.name;
                $.ajax({
                    url: 'sign_up',
                    dataType: "json",
                    type: 'POST',
                    data: { hour },
                    success: function() {
                        
                        $("#slot"+event.target.value+"").append("<li> <small><button id='leave' name='"+ id +"' value='" + event.target.value + "' class='btn col-10 btn-sm btn-danger'>"+ name + "</button></small> </li><br>");
                    },
                    error: function() {
                        alert("Sign up failed");
                    }

                });

         });
         if(notsigned)
            alert("Must use the search to the right and check the boxes of people you want to signed up");
    } else if (event.target.id == 'leave') {

        var hour = { volunteer_id: event.target.name, section_id: event.target.value }
        $.ajax({
            url: 'leave',
            dataType: "json",
            type: 'POST',
            data: { hour },
            success: function(data) {
                $("#slot"+event.target.value+" button[name='" + event.target.name + "'").hide();
                alert("Successly removed" + event.target.text);
            },
            error: function() {
                alert("faiiled");
            }
        });
    }
});
$('span').click(function() {
$('#modal').slideUp("slow");

});


  
  


  $("#name ").keyup(function(e){
    $("#mylist li").each(function(){
      var str = this.id.toLowerCase();
   
      var filter = e.target.value.toLowerCase();
      var res = str.match("(.*|\s?)"+filter+".*");
      if(e.target.value == "")
        $("#results").hide();
      else
        $("#results").show();
      
      if(res != null)
        $(this).show();
      else
        $(this).hide();
    });
  });



</script>

volunteerlogging/app/views/events/createSections.js.erb
alert("hit");
$('#calendar').fullCalendar(
  'renderEvent', 
  "<%= @newevent %>",
  true
);
$('.modal').modal('hide');

volunteerlogging/app/views/events/create_event.js.erb
$('#content').html('<%= j render "form" %>');
$('#modal').slideDown("slow");

volunteerlogging/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

volunteerlogging/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>


<style>


#cal-back {
    background-color: white;
    margin-top: 20px;
}

</style>
<div id="cal-back" class="jumbotron col-10 offset-1">

  <div id="calendar">
  </div>
  <%= link_to 'Back', '/volunteers/home', :class=>"btn col-2 offset-9"%>

</div>


<script>
var initialize_calendar;
var vol;
$("#modal").slideUp(0);

$.ajax({
    url: "/signed_in",
    type: "get",
    dataType: "json",
    success: function(data) {
         vol = data;
    }
});


initialize_calendar = function() {
    $('#calendar').fullCalendar({
       height: 500,
        width: 400,
        events: '/events.json',

        eventClick: function(event, jsEvent, view) {

             
            $.ajax({
                url: 'event/showEvent',
                dataType: "json",
                type: "GET",
                data: { id: event.id },
                success: function(data) {
                    $("#content").html("");
                    var desc = data["desc"]

                    $("#description").html("<h5>Description:</h5> " + desc[0]["description"]);
                    var a = "";
                    var count = 1;
                    var signup = true;

                    data[0].forEach(function(num) {
                        a = "<div id='slots" + count + "' class='col-4'>  <h3>Slot " + count + "</h3>";

                        var start = (num.start.substr(11, 2) % 12 == 0 ? 12 : num.start.substr(11, 2) % 12) + ":" + num.start.substr(14, 2) + (num.start.substr(11, 2) < 12 ? 'am' : 'pm');

                        var end = (num.end.substr(11, 2) % 12 == 0 ? 12 : num.end.substr(11, 2) % 12) + ":" + num.end.substr(14, 2) + (num.end.substr(11, 2) < 12 ? 'am' : 'pm');

                        a += "<p>" + start + " - " + end + "</p>";
                        a += "<ul id='slot"+ num.id +"' class='list-unstyled'>";
                        data[num.id].forEach(function(person) {
                           
                            
                                a += " <li> <small><button id='leave' name='"+ person.id +"' value='" + num.id + "' class='btn col-10 btn-sm btn-danger'>"+person.firstName + " " + person.lastName + "</button></small> </li><br>";

                           
                        });
                        a += "</ul><button  id='signup'  value='" + num.id + "' class='btn btn-md btn-primary'>Sign Up</button><br>";

                        a += "</div>";
                        $("#content").append(a);
                        count++;
                    });


                    $('#modal').slideDown("slow");

                },
                error: function() {
                    alert("didnt work");
                }
            });
            return false;
        },
        dayClick: function(date, jsEvent, view) {

           
          if(<%= current_admin.to_json.html_safe %>){
            $.getScript('/create_event', function(data) {
                $("#event_start_date").val(date.format());
                $("#event_end_date").val(date.format());
                 $("#event_start_time").val("08:00");
                 $("#event_end_time").val("09:00");
            
            });
          }
        }
    });

}
$(document).on('turbolinks:load', initialize_calendar);

$(document).on('click', 'button', function(event) {
    
var vol = <%= current_volunteer.to_json.html_safe%>
    if (event.target.id == 'signup') {

        
            
            
            var hour = { section_id: event.target.value, volunteer_id: vol.id, hoursWorked: 1};
                
                $.ajax({
                    url: '/sign_up',
                    dataType: "json",
                    type: 'POST',
                    data: { hour },
                    success: function(data) {
                        if (data.failed == true)
                          alert("You can not sign in twice for the same section");
                        else{
                        $("#slot"+event.target.value+"").append("<li> <small><button id='leave' name='"+ vol.id +"' value='" + event.target.value + "' class='btn col-10 btn-sm btn-danger'>"+ vol.firstName + " " + vol.lastName + "</button></small> </li><br>");
                        }
                    },
                    error: function() {
                        alert("Sign up failed");
                    }

                });

        
         
    } else if (event.target.id == 'leave') {
        if(vol.id == event.target.name){
            
        var hour = { volunteer_id: event.target.name, section_id: event.target.value };
        $.ajax({
            url: 'leave',
            dataType: "json",
            type: 'POST',
            data: { hour },
            success: function(data) {
                $("#slot"+event.target.value+" button[name='" + event.target.name + "'").hide();
                alert("Successly removed" + event.target.name);
            },
            error: function() {
                alert("faiiled");
            }
        });
        }else{
            alert("You can not log anyone else out");
        }

    }
});
$('span').click(function() {
$('#modal').slideUp("slow");
});
</script>

volunteerlogging/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

volunteerlogging/app/views/events/new.js.erb
$('.modal-content').html("<%= j (render 'form') %>");
$('#newEventModal').show(); 

volunteerlogging/app/views/events/sections.js.erb
$("#inside-modal").html("<%= j render('eventSec') %>");
$("#newEventModal").show();

volunteerlogging/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

volunteerlogging/app/views/events/showEvent.js.erb
$(".modal-content").html("<%= j render('eventSec') %>");
$("#newEventModal").show();

volunteerlogging/app/views/events/sign_up.js.erb
$("#notice").html("Hour created");
$("#notice").show();

volunteerlogging/app/views/events/updateCal.js.erb
$('.calendar').fullCalendar(
  'renderEvent', 
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');