volunteerlogging/config/routes.rb
Rails.application.routes.draw do
  resources :sections

  resources :events
  mount RailsAdmin::Engine => '/super_admin', as: 'rails_admin'
  devise_for :admins, path: 'admin', controllers: { sessions: "admins/sessions" , registrations: "admins/registrations"}
  devise_for :volunteers, path: 'volunteer', controllers: { sessions: "volunteers/sessions" , registrations: "volunteers/registrations"}
  
  

  root 'pages#home'  
  get 'pages/home'

  get 'event/showEvent', to: 'events#showEvent', as: "eshow"  
  get 'event/sections', to: 'events#sections'
  get 'create_event', to: 'events#create_event'
  post 'sign_up', to: 'events#sign_up'
  get 'signed_in', to: 'application#current_user'
  post 'leave', to: 'events#leave'
  post 'event/create_sections', to: 'events#createSections'
  get  'event/create_sections', to: 'events#new'
  get 'section', to: "events#eventSections"
  get 'admin_cal', to: "events#admin_cal"
  get 'updateCal', to: "events#updateCal"

  get 'pages/about'
  get 'volunteers/home', to: 'volunteers#home'
  get 'volunteers/descriptions', to:'volunteers#descriptions'
  get 'volunteers/hoursworked', to: "volunteers#hoursworked"

  get 'admins/dashboard', to: 'admins#dashboard'
  get 'admins/volunteers', to: 'admins#volunteers'
   get 'admins/volunteers/:id', to: 'volunteers#show'
  get 'admins/volunteers/:id/edit', to: 'volunteers#edit'
  delete 'admins/volunteers/:id', to: 'volunteers#destroy'
  get 'admins/log_hours', to: 'hours#new'
  post 'admins/log_hours', to: 'hours#create'
  get 'admins/register', to: 'volunteers#new'
  get 'admins/reports', to: 'reports#reports'
  get 'admins/email', to: 'admins#email_users'
  post 'admins/email', to: 'admins#send_emails'

  get 'calendar', to: 'calendar#calendar'

  resources :admins, :controller => 'admins'
  resources :volunteer_descriptions
  resources :volunteers
  resources :hours
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

volunteerlogging/app/models/section.rb
class Section < ApplicationRecord
    belongs_to :event
    has_many :hours
end

volunteerlogging/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
    
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      
      params.require(:section).permit(:event_id, :start, :end, :event_section)
      
    end
end

volunteerlogging/app/helpers/sections_helper.rb
module SectionsHelper
end

volunteerlogging/app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <br>
  <div class="row col-12">
    <label class="col-3 text-right">section event</label>
    <%= form.text_field :event_section, :class=>"col-3 form-control" %>
  
    <label class="col-3 text-right">event </label>
    <%= form.text_field :event_id, :class=>"col-3 form-control" %>
  </div>
    <br>
   <%= form.label :start_time %>
    <%= form.datetime_select :start %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

volunteerlogging/app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

volunteerlogging/app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h3>Slot 1</h3>
</div>

volunteerlogging/app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

volunteerlogging/app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>

volunteerlogging/app/views/sections/sign_up.js.erb
$('#modal-content').html("<%= j (render section_path) %>");
$('#newEventModal').slideDown(350);