volunteerlogging/config/routes.rb
Rails.application.routes.draw do
  resources :sections

  resources :events
  mount RailsAdmin::Engine => '/super_admin', as: 'rails_admin'
  devise_for :admins, path: 'admin', controllers: { sessions: "admins/sessions" , registrations: "admins/registrations"}
  devise_for :volunteers, path: 'volunteer', controllers: { sessions: "volunteers/sessions" , registrations: "volunteers/registrations"}
  
  

  root 'pages#home'  
  get 'pages/home'

  get 'event/showEvent', to: 'events#showEvent', as: "eshow"  
  get 'event/sections', to: 'events#sections'
  get 'create_event', to: 'events#create_event'
  post 'sign_up', to: 'events#sign_up'
  get 'signed_in', to: 'application#current_user'
  post 'leave', to: 'events#leave'
  post 'event/create_sections', to: 'events#createSections'
  get  'event/create_sections', to: 'events#new'
  get 'section', to: "events#eventSections"
  get 'admin_cal', to: "events#admin_cal"
  get 'updateCal', to: "events#updateCal"

  get 'pages/about'
  get 'volunteers/home', to: 'volunteers#home'
  get 'volunteers/descriptions', to:'volunteers#descriptions'
  get 'volunteers/hoursworked', to: "volunteers#hoursworked"

  get 'admins/dashboard', to: 'admins#dashboard'
  get 'admins/volunteers', to: 'admins#volunteers'
   get 'admins/volunteers/:id', to: 'volunteers#show'
  get 'admins/volunteers/:id/edit', to: 'volunteers#edit'
  delete 'admins/volunteers/:id', to: 'volunteers#destroy'
  get 'admins/log_hours', to: 'hours#new'
  post 'admins/log_hours', to: 'hours#create'
  get 'admins/register', to: 'volunteers#new'
  get 'admins/reports', to: 'reports#reports'
  get 'admins/email', to: 'admins#email_users'
  post 'admins/email', to: 'admins#send_emails'

  get 'calendar', to: 'calendar#calendar'

  resources :admins, :controller => 'admins'
  resources :volunteer_descriptions
  resources :volunteers
  resources :hours
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

volunteerlogging/app/models/volunteer_description.rb
class VolunteerDescription < ApplicationRecord
	belongs_to :volunteers
end

volunteerlogging/app/controllers/volunteer_descriptions_controller.rb
class VolunteerDescriptionsController < ApplicationController
  before_action :set_volunteer_description, only: [:show, :edit, :update, :destroy]

  # GET /volunteer_descriptions
  # GET /volunteer_descriptions.json
  def index
    @volunteer_descriptions = VolunteerDescription.all
  end

  # GET /volunteer_descriptions/1
  # GET /volunteer_descriptions/1.json
  def show
  end

  # GET /volunteer_descriptions/new
  def new
    @volunteer_description = VolunteerDescription.new
  end

  # GET /volunteer_descriptions/1/edit
  def edit
  end

  # POST /volunteer_descriptions
  # POST /volunteer_descriptions.json
  def create
    @volunteer_description = VolunteerDescription.new(volunteer_description_params)

    respond_to do |format|
      if @volunteer_description.save
        format.html { redirect_to @volunteer_description, notice: 'Volunteer description was successfully created.' }
        format.json { render :show, status: :created, location: @volunteer_description }
      else
        format.html { render :new }
        format.json { render json: @volunteer_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteer_descriptions/1
  # PATCH/PUT /volunteer_descriptions/1.json
  def update
    respond_to do |format|
      if @volunteer_description.update(volunteer_description_params)
        format.html { redirect_to @volunteer_description, notice: 'Volunteer description was successfully updated.' }
        format.json { render :show, status: :ok, location: @volunteer_description }
      else
        format.html { render :edit }
        format.json { render json: @volunteer_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteer_descriptions/1
  # DELETE /volunteer_descriptions/1.json
  def destroy
    @volunteer_description.destroy
    respond_to do |format|
      format.html { redirect_to volunteer_descriptions_url, notice: 'Volunteer description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer_description
      @volunteer_description = VolunteerDescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volunteer_description_params
      params.require(:volunteer_description).permit(:volunteerId, :infoVolunteer, :datesAvail)
    end
end

volunteerlogging/app/helpers/volunteer_descriptions_helper.rb
module VolunteerDescriptionsHelper
end

volunteerlogging/app/views/volunteer_descriptions/_form.html.erb
<%= form_with(model: volunteer_description, local: true) do |form| %>
  <% if volunteer_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(volunteer_description.errors.count, "error") %> prohibited this volunteer_description from being saved:</h2>

      <ul>
      <% volunteer_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>

  <div id="" class="jumbotron row col-sm-9 offset-2">
    <div class="row col-12">
      <h2 class="col-3 offset-4">Descriptions</h2>
    </div>

    <div>
      <br>
      <form>
        <div class="row col-12">
          <label class="col-3 text-right">ID:</label>
          <%= form.text_field :volunteerId, id: :volunteer_description_volunteerId,
           :class=>"col-2 form-control" %>
        
        
        
          <label class="col-2 text-right">Date Available:</label>
          <%= form.date_select :datesAvail, id: :volunteer_description_datesAvail, :class=>"col-2 form-control" %>
        </div>
        <br>
        <div class="row col-12">
          <label class="col-3 text-right">Extra Info:</label>
          <%= form.text_area :infoVolunteer, id: :volunteer_description_infoVolunteer, :class=>"col-9 form-control" %>
        </div>
        <br>

        <div class="row col-12">

        <%= form.submit :class=>"btn col-5 offset-1" %>
        <%= link_to "Back", "/admins/dashboard", :class=>"btn col-2 offset-3" %>
      </div>
      </form>
    </div>
    
  </div>


<% end %>

volunteerlogging/app/views/volunteer_descriptions/edit.html.erb
<h1>Editing Volunteer Description</h1>

<%= render 'form', volunteer_description: @volunteer_description %>

<%= link_to 'Show', @volunteer_description %> |
<%= link_to 'Back', volunteer_descriptions_path %>

volunteerlogging/app/views/volunteer_descriptions/index.html.erb
<style>
.jumbotron {
  margin-top: 10%;
  background-color:white;
}

table{
  margin-top: 5%;
}
</style>
<p id="notice"><%= notice %></p>

<div id ="" class="jumbotron col-10 offset-1 ">
<div class="row">
<h1 class="col-4 offset-4">Volunteer Descriptions</h1>
<input  id="search" class="form-control col-3 offset-1" type="search" placeholder="Search">
</div>
<table class="table table-sm table-hover table-responsive">
  <thead>
    <tr>
      <th id="volunteerId">Volunteer ID</th>
      <th id="datesAvail">Available Date</th>
      <th id="infoVolunteer">More Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
   <!-- <% @volunteer_descriptions.each do |volunteer_description| %>
      <tr>
        <td><%= volunteer_description.volunteerId %></td>
        <td><%= volunteer_description.infoVolunteer %></td>
        <td><%= volunteer_description.datesAvail %></td>
        <td><%= link_to 'Show', volunteer_description %></td>
        <td><%= link_to 'Edit', edit_volunteer_description_path(volunteer_description) %></td>
        <td><%= link_to 'Destroy', volunteer_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    !-->
  </tbody>
</table>
<div class="row">
<%= link_to 'New Volunteer Description', new_volunteer_description_path, :class=>"btn col-3" %>
<%= link_to "Back", "/admins/dashboard", :class=>"btn col-2 offset-7" %>
</div>
</div>
<br>

<script>
  
  var data = <%= @volunteer_descriptions.to_json.html_safe %>

  function sortrows(cat, e ){

  data.sort(function(a,b){
    var a1 = a[cat], b1 = b[cat];
    if(a1 == b1 ) return 0;
    return a1 > b1? 1: -1;
  });

  var tbody = "";
  $.each(data, function(key, obj){
    
    tbody +="<tr>";
    tbody += "<td>"+ obj.volunteer_id + "</td>";
    tbody += "<td>"+ obj.datesAvail + "</td>";
    tbody += "<td>"+ obj.infoVolunteer + "</td>";
    tbody += "<td><a href='volunteer_descriptions/"+ obj.id +"'>Show</a></td>";
    tbody += "<td><a href='volunteer_descriptions/"+ obj.id +"/edit'>Edit</a></td>";
    tbody += "<td><a data-method='delete' href='volunteer_descriptions/"+ obj.id +"'>Delete</a></td>";
    tbody += "</tr>";
  });
  
  $("tbody").html(tbody);
  }

  $("#search").keyup(function(e){
    $("table .trs").each(function(){
      var str = $(this).children("#firstName").text().toLowerCase() + " " + $(this).children("#lastName").text().toLowerCase();
   
      var filter = e.target.value.toLowerCase();
      
      var res = str.match("(.*|\s?)"+filter+".*");
      
      if(res == null)
        $(this).hide();
      else
        $(this).show();
    });
  });  

  $("th").click(function(e){
    sortrows(e.target.id);
  });

  sortrows("id");
</script>

volunteerlogging/app/views/volunteer_descriptions/new.html.erb
<h1>New Volunteer Description</h1>

<%= render 'form', volunteer_description: @volunteer_description %>

<%= link_to 'Back', volunteer_descriptions_path %>

volunteerlogging/app/views/volunteer_descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Volunteerid:</strong>
  <%= @volunteer_description.volunteerId %>
</p>

<p>
  <strong>Infovolunteer:</strong>
  <%= @volunteer_description.infoVolunteer %>
</p>

<p>
  <strong>Datesavail:</strong>
  <%= @volunteer_description.datesAvail %>
</p>

<%= link_to 'Edit', edit_volunteer_description_path(@volunteer_description) %> |
<%= link_to 'Back', volunteer_descriptions_path %>